# 日本語版ジョブクラフティング尺度
problem = Problem.create(title: '日本語版ジョブクラフティング尺度', text: '仕事の「やりがい」を決める21問')
Division.create(division_id: 1,text: '構造的な仕事の資源の向上',standard: 14,max: 25,problem_id: problem.id)
Division.create(division_id: 2,text: '妨害的な仕事の要求度の低減',standard: 12,max: 30,problem_id: problem.id)
Division.create(division_id: 3,text: '対人関係における仕事の資源の向上',standard: 9,max: 25,problem_id: problem.id)
Division.create(division_id: 4,text: '挑戦的な仕事の要求度の向上',standard: 10,max: 25,problem_id: problem.id)
Question.create(number: 1,text: '私は、自分の能力を伸ばすようにしている',division_id: 1,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 2,text: '私は、自分自身の専門性を高めようとしている',division_id: 1,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 3,text: '私は、仕事で新しいことを学ぶようにしている',division_id: 1,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 4,text: '私は、自分の能力を最大限に生かせるように心がけている',division_id: 1,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 5,text: '私は、自分の仕事のやり方を自分自身で決めている',division_id: 1,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 6,text: '私は、仕事で思考力が消耗しすぎないようにしている',division_id: 2,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 7,text: '私は、自分の仕事で感情的に張りつめないように心がけている',division_id: 2,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 8,text: '私は、自分の感情を乱すような問題を抱えている人との関わりをできるだけ減らすように自分の仕事に取り組んでいる',division_id: 2,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 9,text: '私は、非現実的な要求をしてくる人とのかかわりをできるだけ減らすように自分の仕事を調整している',division_id: 2,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 10,text: '私は、困難な決断をたくさんしなくてもいいように自分の仕事を調整している',division_id: 2,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 11,text: '私は、一度に長時間にわたって集中しなくてもいいように自分の仕事を調整している',division_id: 2,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 12,text: '私は、上司に自分を指導してくれるように求める',division_id: 3,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 13,text: '私は、上司が私の仕事に満足しているかどうか尋ねている',division_id: 3,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 14,text: '私は、上司に仕事で触発される機会を求める',division_id: 3,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 15,text: '私は、仕事の成果に対するフィードバックを他者に求める',division_id: 3,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 16,text: '私は、同僚に助言を求める',division_id: 3,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 17,text: '面白そうな企画があるときには，積極的にプロジェクトメンバーとして立候補する',division_id: 4,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 18,text: '仕事で新しい発展があれば，いち早くそれを調べ、自ら試してみる',division_id: 4,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 19,text: '今の仕事であまりやることがないときは，新しいプロジェクトを始めるチャンスととらえる',division_id: 4,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 20,text: '私は、金銭的な報酬が追加されなくても自分に課された以上の仕事を率先してこなしている',division_id: 4,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 21,text: '私は、職務の様々な側面のつながりをよく考えながら自分の仕事がさらに挑戦しがいのあるようにしている',division_id: 4,valuation: 5,inversion: 0,problem_id: problem.id)
