# ワーク・エンゲージメント尺度
problem = Problem.create(title: 'ワーク・エンゲージメント尺度', text: '「自分は仕事にやりがいを感じているか？」を判断できるテスト')
Division.create(division_id: 1,text: '活力',standard: 21,max: 42,problem_id: problem.id)
Division.create(division_id: 2,text: '熱意',standard: 17,max: 35,problem_id: problem.id)
Division.create(division_id: 3,text: '没頭',standard: 21,max: 42,problem_id: problem.id)
Question.create(number: 1,text: '仕事をしていると、活力がみなぎるように感じる。',division_id: 1,valuation: 7,inversion: 0,problem_id: problem.id)
Question.create(number: 2,text: '自分の仕事に、意義や価値を大いに感じる。 ',division_id: 2,valuation: 7,inversion: 0,problem_id: problem.id)
Question.create(number: 3,text: '仕事をしていると、時間がたつのが速い。 ',division_id: 3,valuation: 7,inversion: 0,problem_id: problem.id)
Question.create(number: 4,text: '職場では、元気が出て精力的になるように感じる。',division_id: 1,valuation: 7,inversion: 0,problem_id: problem.id)
Question.create(number: 5,text: '仕事に熱心である。 ',division_id: 2,valuation: 7,inversion: 0,problem_id: problem.id)
Question.create(number: 6,text: '仕事をしていると、他のことはすべて忘れてしまう。',division_id: 3,valuation: 7,inversion: 0,problem_id: problem.id)
Question.create(number: 7,text: '仕事は、私に活力を与えてくれる。',division_id: 2,valuation: 7,inversion: 0,problem_id: problem.id)
Question.create(number: 8,text: '朝に目がさめると、さあ仕事へ行こう、という気持ちになる。',division_id: 1,valuation: 7,inversion: 0,problem_id: problem.id)
Question.create(number: 9,text: '仕事に没頭しているとき、幸せだと感じる。',division_id: 3,valuation: 7,inversion: 0,problem_id: problem.id)
Question.create(number: 10,text: '自分の仕事に誇りを感じる。',division_id: 2,valuation: 7,inversion: 0,problem_id: problem.id)
Question.create(number: 11,text: '私は仕事にのめり込んでいる。',division_id: 3,valuation: 7,inversion: 0,problem_id: problem.id)
Question.create(number: 12,text: '長時間休まずに、働き続けることができる。',division_id: 1,valuation: 7,inversion: 0,problem_id: problem.id)
Question.create(number: 13,text: '私にとって仕事は、意欲をかきたてるものである。',division_id: 2,valuation: 7,inversion: 0,problem_id: problem.id)
Question.create(number: 14,text: '仕事をしていると、つい夢中になってしまう。',division_id: 3,valuation: 7,inversion: 0,problem_id: problem.id)
Question.create(number: 15,text: '職場では、気持ちがはつらつとしている。',division_id: 1,valuation: 7,inversion: 0,problem_id: problem.id)
Question.create(number: 16,text: '仕事から頭を切り離すのが難しい。',division_id: 3,valuation: 7,inversion: 0,problem_id: problem.id)
Question.create(number: 17,text: 'ことがうまく運んでいないときでも、辛抱強く仕事をする。',division_id: 1,valuation: 7,inversion: 0,problem_id: problem.id)