# 自己実現レベルテスト
problem = Problem.create(title: '自己実現レベルテスト', text: '「自分の自己実現レベルはどれぐらいなの？」を判断できるテスト')
Division.create(division_id: 1,text: '新鮮な評価の継続',standard: 6,max: 15,problem_id: problem.id)
Division.create(division_id: 2,text: 'アクセプタンス',standard: 6,max: 15,problem_id: problem.id)
Division.create(division_id: 3,text: '真正性',standard: 6,max: 15,problem_id: problem.id)
Division.create(division_id: 4,text: '平静さ',standard: 6,max: 15,problem_id: problem.id)
Division.create(division_id: 5,text: '目的',standard: 6,max: 15,problem_id: problem.id)
Division.create(division_id: 6,text: '現実の効率的な認識',standard: 6,max: 15,problem_id: problem.id)
Division.create(division_id: 7,text: '人道主義',standard: 6,max: 15,problem_id: problem.id)
Division.create(division_id: 8,text: 'ピーク体験',standard: 6,max: 15,problem_id: problem.id)
Division.create(division_id: 9,text: '優れた道徳的直感',standard: 6,max: 15,problem_id: problem.id)
Division.create(division_id: 10,text: '創造性',standard: 6,max: 15,problem_id: problem.id)
Question.create(number: 1,text: '他の人にとっては陳腐に思えるような人生の基本的なものごとに対して、新鮮さと、素朴さと、畏敬の念と、喜びと、驚きと、時には恍惚の感情をもって、何度でも味わうことができる。',division_id: 1,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 2,text: '夕焼けを見るたびに美しいと思う。',division_id: 1,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 3,text: '自分の人生の中にある良いものに対しては、何度見ても感謝の気持ちを感じる。',division_id: 1,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 4,text: '欠点も含めて、私は自分のすべての側面を受け入れている。',division_id: 2,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 5,text: '自分が持っている悪癖や負の願望について、私は恥や申し訳なさの感情を持たずに受け入れている。',division_id: 2,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 6,text: '自分が持っている悪癖や負の願望を、私は無条件に受け入れている。',division_id: 2,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 7,text: '周囲が悪いことをしているような環境や状況であっても、私は自分の尊厳と誠実さを保つことができる。',division_id: 3,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 8,text: '自分の核となる価値観が揺らぎそうな環境にあっても、自己の価値観に忠実でいることができる。',division_id: 3,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 9,text: '私は自分の行動に責任を持つことができる。',division_id: 3,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 10,text: 'たいていの人が悩むようなことでも、私は平静で動じずにいる装っていることが多い。',division_id: 4,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 11,text: '厳しい試練、障害、喪失、フラストレーションなどに直面しても、私は比較的平静でいることができる。',division_id: 4,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 12,text: '人生の避けられない浮き沈みに対して、優雅さと、受容の気持ちと、平静さをもって取り組むことができる。',division_id: 4,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 13,text: '人生の中で特定のミッションを達成することに大きな責任と義務を感じている。',division_id: 5,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 14,text: '現世で果たすべき重要な任務があるように感じている。',division_id: 5,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 15,text: '私は、人類全体のメリットになりそうな人生の目的を持っている。',division_id: 5,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 16,text: '私は現実を明確に認識していることが多い。',division_id: 6,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 17,text: '私は常に人や自然の本当の真実に迫ろうとしている。',division_id: 6,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 18,text: 'できるだけ世界の現実に認識を近づけようと努力している。',division_id: 6,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 19,text: '私はすべての人類に対して、深い一体感を持っている。',division_id: 7,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 20,text: '私はすべての人間に対して、深い共感と愛情を感じている。',division_id: 7,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 21,text: '私は、人類を助けたいという純粋な願望を持っている。',division_id: 7,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 22,text: '私は、自分自身や他の人たちに新たな展望や可能性が開かれていると感じることがよくあります。',division_id: 8,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 23,text: '私はしばしば、自分の利己的な関心事を超えたと感じられるような経験をしている。',division_id: 8,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 24,text: '私はしばしば、この地球上のすべての人々や物事と一体感を感じるような経験をしている。',division_id: 8,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 25,text: '私は自分の道徳的な判断を、あまり深く考えずに信頼している。',division_id: 9,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 26,text: '私は日常生活の中で強い「良し悪し」の感覚を持っている。',division_id: 9,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 27,text: '自分が何か悪いことをしたら、「心の底から」すぐにわかる。',division_id: 9,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 28,text: '私は、自分がすることについて全体的にクリエイティブな精神を発揮している。',division_id: 10,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 29,text: '自分の仕事のすべてに対して、創造的な態度を持ってのぞんでいる。',division_id: 10,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 30,text: '私は自分の中にいる「子供」に従ってよく自由に行動している。',division_id: 10,valuation: 5,inversion: 0,problem_id: problem.id)