# セルフコンパッションスケール
problem = Problem.create(title: 'セルフコンパッションスケール', text: 'メンタルヘルスの維持に欠かせない「セルフコンパッション」のレベルが自分はどれだけ高いのか？を判断する26問')
Division.create(division_id: 1,text: '自己への優しさ',standard: 14,problem_id: problem.id)
Division.create(division_id: 2,text: '自己批判レベル',standard: 16,problem_id: problem.id)
Division.create(division_id: 3,text: '共通の人間性',standard: 11,problem_id: problem.id)
Division.create(division_id: 4,text: '孤立',standard: 11,problem_id: problem.id)
Division.create(division_id: 5,text: 'マインドフルネス',standard: 12,problem_id: problem.id)
Division.create(division_id: 6,text: '過剰な自己同一化',standard: 12,problem_id: problem.id)
Question.create(number: 1,text: '私は自分の欠点や不十分な点を許せず、批判的な態度を取る。',division_id: 2,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 2,text: '気分が落ち込ん だときには、間違ったことすべてについて、くよくよと心配し、こだわる傾向にある。',division_id: 6,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 3,text: 'なんらかの悪いことが起きたときは、その困難のことを、誰もが経験する人生の一部としてとらえる。',division_id: 3,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 4,text: '自分の能力不足について考えると、自分が世の中から引き離されたような気分になる。',division_id: 4,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 5,text: '感情的な苦痛を感じているとき、自分に優しい感情を向けるようにしている。',division_id: 1,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 6,text: '大切なことで失敗すると、力不足の感覚にさいなまれる。',division_id: 6,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 7,text: '気持ちが落ち込んだま外出しなければならないときは、世界には自分と同じような感情を持つ人がたくさんいるという事実を思い出すようにしている。',division_id: 3,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 8,text: '本当に大きな困難が起きているときは、自分に厳しくしがちだ。',division_id: 2,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 9,text: '気分を害したときには、自分の感情をバランスよく保とうとする。',division_id: 5,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 10,text: '何らかの形で自分が無能だという気持ちになったとき、私は「自分の能力のなさを辛く感じるのは誰にでもあることだ」と自分に言い聞かせるようにしている。',division_id: 3,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 11,text: '自分自身の嫌な性格ががまんできずにイライラする。',division_id: 2,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 12,text: '大変なトラブルが起きているときは、私は自分自身に思いやりと優しさを与えるようにしている。',division_id: 1,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 13,text: '気分が落ち込むと、大抵の人が私より幸せそうだと感じる。',division_id: 4,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 14,text: 'なにか心が痛むことが起こったら、その状況をバランスよく見ようと心がける。',division_id: 5,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 15,text: '自分の失敗のことを、人間として生きることの一部として考えようとしている。',division_id: 3,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 16,text: '自分の嫌いな面を見ると、自分に腹が立つ。',division_id: 2,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 17,text: '自分にとって大切なことに失敗したら、物事を大きな視点から捉えるようにしている。',division_id: 5,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 18,text: '本当に苦しい時は、他の人は自分よりも気楽な時間を過ごしているのだろうと思いやすい。',division_id: 4,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 19,text: 'なんらかの苦しみを感じているときは、自分自身に親切にするようにしている。',division_id: 1,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 20,text: 'なにか気分を害するようなことが起きると、感情に流されてしまう。',division_id: 6,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 21,text: 'なんらかの苦しみを感じているときは、自分自身に少し冷たくなってしまう。',division_id: 2,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 22,text: '気分が落ち込んでいるときは、好奇心と寛大な心を持って自分の気持ちにアプローチするようにしている。',division_id: 5,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 23,text: '自分自身の欠点と不十分なところについては，やさしい目 で見るようにしている。',division_id: 1,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 24,text: '何か苦痛を感じることが起こったとき、その出来事を大げさに考える傾向がある。',division_id: 6,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 25,text: '自分にとって大切な何かに失敗したとき、ひとりぼっちでいるように感じる傾向がある。',division_id: 4,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 26,text: '自分のパーソナリティの好きでな いところについては理解し、やさしい目で見るようにしている。',division_id: 1,valuation: 5,inversion: 0,problem_id: problem.id)
