# プランフルネス・スケール
problem = Problem.create(title: 'プランフルネス・スケール', text: '自分がゴールを達成できないのはなぜか？がよくわかる30問')
Division.create(division_id: 1,text: '精神の柔軟性(感情コントロール)',standard: 35,problem_id: problem.id)
Division.create(division_id: 2,text: '認知戦略(プランニング)',standard: 35,problem_id: problem.id)
Division.create(division_id: 3,text: '時間感覚(長期的な視野)',standard: 35,problem_id: problem.id)
Question.create(number: 1,text: '事前の計画を立てるときは、過去に犯したミスから学んだことを考慮するようにしている',division_id: 3,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 2,text: 'ときどき役に立たない計画を思いついてしまう',division_id: 2,valuation: 5,inversion: 1,problem_id: problem.id)
Question.create(number: 3,text: '何らかの決断をするときには、私は主に現在の状態をもとに判断を行う',division_id: 3,valuation: 5,inversion: 1,problem_id: problem.id)
Question.create(number: 4,text: '綿密に計画して行動するよりも、起きたことに随時対処して行くのが好きだ',division_id: 2,valuation: 5,inversion: 1,problem_id: problem.id)
Question.create(number: 5,text: '何かを達成したいときはゴールを設定する',division_id: 2,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 6,text: '何かを達成しようと思ったのにつまづいたときは、気持ちをもどすのが難しい',division_id: 1,valuation: 5,inversion: 1,problem_id: problem.id)
Question.create(number: 7,text: 'いまの時点で、長期的なゴールをどのように達成できるかどうかのビジョンがある',division_id: 3,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 8,text: '何か大事な目標があるときは、明確なプランを作る',division_id: 2,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 9,text: '目標達成の過程で障害が起きたら、ゴールのことを考えて気を取り直す',division_id: 1,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 10,text: '日々の雑事をこなすうちに、長期的なゴールを達成するための道筋から逸れてしまいやすい',division_id: 1,valuation: 5,inversion: 1,problem_id: problem.id)
Question.create(number: 11,text: '自分の未来がどうなるかについて考えることはほとんどない',division_id: 3,valuation: 5,inversion: 1,problem_id: problem.id)
Question.create(number: 12,text: '毎日同じようなルーティンを繰り返しているとマンネリ化した気分になる',division_id: 2,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 13,text: '自分の計画を進めるのが難しい時がある',division_id: 1,valuation: 5,inversion: 1,problem_id: problem.id)
Question.create(number: 14,text: '自分の時間とエネルギーの大半は、将来に欲しいものを手に入れるために費やしている',division_id: 3,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 15,text: '毎日少しずつタスクをこなしてゴールを達成している',division_id: 2,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 16,text: 'ゴールに集中しているときに、誘惑に勝つことができる',division_id: 1,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 17,text: '自分のゴールを達成するための明確な手段についてよく考える',division_id: 2,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 18,text: 'スケジュール通りに動くよりも、無計画に行動するのが好きだ',division_id: 2,valuation: 5,inversion: 1,problem_id: problem.id)
Question.create(number: 19,text: '難しくて興味がわかないタスクでも、それがゴール達成に役立つのなら実行できる',division_id: 1,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 20,text: '未来のゴールについて集中するのは難しい',division_id: 3,valuation: 5,inversion: 1,problem_id: problem.id)
Question.create(number: 21,text: '細かいプランを作るのはストレスだ',division_id: 2,valuation: 5,inversion: 1,problem_id: problem.id)
Question.create(number: 22,text: 'ゴールに向かう作業が難しくて困ったら、その作業をやめてしまうことがある',division_id: 1,valuation: 5,inversion: 1,problem_id: problem.id)
Question.create(number: 23,text: '自分のゴールから注意をそらすような事態を改善するために、過去の経験を振り返ることがある',division_id: 3,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 24,text: 'いまやっていることが、どのように未来のゴールに結びついているのかをすぐに理解できる',division_id: 1,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 25,text: '未来の感情よりも今の幸福を優先する',division_id: 3,valuation: 5,inversion: 1,problem_id: problem.id)
Question.create(number: 26,text: '大きなプロジェクトをこなすときは、小さなステップに分解する',division_id: 2,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 27,text: '今日の行動を考えるときは、それが明日にどのような意味を持つのかを合わせて考える',division_id: 1,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 28,text: '過去にどんなゴールを達成できなかったかを簡単に思い出すことができる',division_id: 3,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 29,text: 'ゴールに向かっているときにミスをすると、それを失敗だととらえてしまう',division_id: 1,valuation: 5,inversion: 1,problem_id: problem.id)
Question.create(number: 30,text: '長期的なゴールについて考えるために時間を使うことはない',division_id: 3,valuation: 5,inversion: 1,problem_id: problem.id)
