# 心理恐怖尺度
problem = Problem.create(title: '心理恐怖尺度', text: '「自分はどんなことについて恐怖を感じやすいのか？」を判断できるテスト')
Division.create(division_id: 1,text: '失敗への恐怖',standard: 3,problem_id: problem.id)
Division.create(division_id: 2,text: '拒絶への恐怖',standard: 3,problem_id: problem.id)
Division.create(division_id: 3,text: 'コントロールを失うことへの恐怖',standard: 3,problem_id: problem.id)
Division.create(division_id: 4,text: '感情的な親密さを失うことへの恐怖',standard: 3,problem_id: problem.id)
Division.create(division_id: 5,text: '評判を失うことへの恐怖',standard: 2,problem_id: problem.id)
Question.create(number: 1,text: '難しい状況で責任を負わされたり依存されるのが怖い',division_id: 1,valuation: 2,inversion: 0,problem_id: problem.id)
Question.create(number: 2,text: '成功するかどうかわからないことをするのは不安だ',division_id: 1,valuation: 2,inversion: 0,problem_id: problem.id)
Question.create(number: 3,text: '問題がすぐに理解できないと不安になる',division_id: 1,valuation: 2,inversion: 0,problem_id: problem.id)
Question.create(number: 4,text: '新しい人と知り合うと、その人に拒絶されるのが怖くなる',division_id: 2,valuation: 2,inversion: 0,problem_id: problem.id)
Question.create(number: 5,text: '見知らぬ人に近づくと、冷たい態度をとられるないか不安になる',division_id: 2,valuation: 2,inversion: 0,problem_id: problem.id)
Question.create(number: 6,text: '他人から拒絶されることは、私にとって大きな脅威を感じさせる',division_id: 2,valuation: 2,inversion: 0,problem_id: problem.id)
Question.create(number: 7,text: '物事をコントロールできなくなると怖くなる',division_id: 3,valuation: 2,inversion: 0,problem_id: problem.id)
Question.create(number: 8,text: '自分が何かに影響を与えることができていないことに気づくと、すぐに心配になる',division_id: 3,valuation: 2,inversion: 0,problem_id: problem.id)
Question.create(number: 9,text: '状況をコントロールできなかったらと考えると、怖くなる',division_id: 3,valuation: 2,inversion: 0,problem_id: problem.id)
Question.create(number: 10,text: '親友との連絡が途絶えたら、私は絶対にショックを受ける',division_id: 4,valuation: 2,inversion: 0,problem_id: problem.id)
Question.create(number: 11,text: '愛する人との感情的なふれあいを失うと動揺する',division_id: 4,valuation: 2,inversion: 0,problem_id: problem.id)
Question.create(number: 12,text: '親しい友人に避けられたら、友人との関係に不安を覚える',division_id: 4,valuation: 2,inversion: 0,problem_id: problem.id)
Question.create(number: 13,text: '自分の評判が危うくなると、とても心配になる',division_id: 5,valuation: 2,inversion: 0,problem_id: problem.id)
Question.create(number: 14,text: '私は自分の評判が下がっていないかどうか、とても気になる',division_id: 5,valuation: 2,inversion: 0,problem_id: problem.id)