# MTQ-10
problem = Problem.create(title: 'MTQ-10', text: '自分のタフさを測る10の質問')
Division.create(division_id: 1,text: 'コントロール',standard: 9,problem_id: problem.id)
Division.create(division_id: 2,text: 'コミットメント',standard: 6,problem_id: problem.id)
Division.create(division_id: 3,text: 'チャレンジ',standard: 7,problem_id: problem.id)
Division.create(division_id: 4,text: 'コンフィデンス',standard: 10,problem_id: problem.id)
Question.create(number: 1,text: '重度なプレッシャーがかかった状況でも冷静にいられる',division_id: 1,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 2,text: 'トラブルが起きる前に、そのことを心配する傾向がある',division_id: 3,valuation: 5,inversion: 1,problem_id: problem.id)
Question.create(number: 3,text: 'やらねばいけないタスクがあるのに、いつもモチベーションを上げるのに苦労する',division_id: 2,valuation: 5,inversion: 1,problem_id: problem.id)
Question.create(number: 4,text: 'どんな問題が起きても、たいていは処理できる',division_id: 4,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 5,text: 'たいていの場合、自分のことを価値がある人間だと感じる',division_id: 4,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 6,text: '一度にいろんなタスクをやらねばならないときは、いつも「どこから手をつけていいかわからない」という気分になる',division_id: 2,valuation: 5,inversion: 1,problem_id: problem.id)
Question.create(number: 7,text: '自分がミスを犯したら、そのことで数日後も心配になる',division_id: 1,valuation: 5,inversion: 1,problem_id: problem.id)
Question.create(number: 8,text: '自分はいつも状況に対処できていると感じる',division_id: 1,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 9,text: 'なにか予期せぬことが起きても、通常は素早く反応できる',division_id: 4,valuation: 5,inversion: 0,problem_id: problem.id)
Question.create(number: 10,text: 'いつも人生の明るい面を見ている',division_id: 3,valuation: 5,inversion: 0,problem_id: problem.id)
